/* CHAT */
export const SAVE_CHAT = "SAVE_CHAT";
export const SAVE_CHAT_SUCCESS = "SAVE_CHAT_SUCCESS";
export const GET_CHAT_BY_ROOM = "GET_CHAT_BY_ROOM";

/* USER */
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

/* MESSAGE */
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const COMPLETE_MESSAGE = "COMPLETE_MESSAGE";
export const COMPLETE_MESSAGE_SUCCESS = "COMPLETE_MESSAGE_SUCCESS";